- name: Add official MariaDB repository
  template:
    src: yum.repos.d_mariadb.repo.j2
    dest: /etc/yum.repos.d/MariaDB.repo
  tags: mariadb

- name: Ensure MySQL packages are installed.
  yum:
    name: "{{ mysql_packages }}"
    state: present
    enablerepo: "{{ mysql_enablerepo | default(omit, true) }}"
  register: rh_mysql_install_packages
